# Generated by Django 4.0.4 on 2022-05-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('CL', 'Closed'), ('DO', 'Done'), ('OP', 'Open')], default='OP', max_length=2),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
